openapi: "3.0.0"
info:
  title: Customer Management
  version: 0.0.1
paths:
  /customer:
    get:
      description: Returns all customers
      responses:
        '200':
          description: A list of customers.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      description: Creating a new customer
      responses:
        '200':
          description: Successfully created a new customer
  /customer/{customerId}:
    get:
      description: Returns a specific customer with a given id
      parameters: 
        - $ref: '#/components/parameters/CustomerId'
      responses:
        '200':
          description: Returns the customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
    put:
      description: Updates a specific customer with a given id
      parameters: 
        - $ref: '#/components/parameters/CustomerId'
      responses:
        '200':
          description: Update was successful
    delete:
      description: Deletes a specific customer with a given id
      parameters: 
        - $ref: '#/components/parameters/CustomerId'
      responses:
        '200':
          description: Successfully deleted customer
components:
  parameters:
    CustomerId:
      name: customerId
      in: path
      required: true
      description: The id of the customer
      schema:
        type: string 
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string